import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, CirclePause, ExternalLink, LoaderCircle, RefreshCw, RotateCcw, Square } from 'lucide-react'
import { api, artifactUrl, type Job } from '../api'
import { Empty, Header } from './shared'
import { jobDestination, jobErrorLabel, jobStageLabel, jobStatusLabel } from './jobPresentation'

export default function JobsPage({industry=''}:{industry?:string}) {
  const [rows,setRows]=useState<Job[]>([]);const [selected,setSelected]=useState<Job|null>(null);const [output,setOutput]=useState('');const [error,setError]=useState('');const [outputError,setOutputError]=useState('');const [viewAll,setViewAll]=useState(!industry)
  const load=useCallback(()=>api<Job[]>('/jobs').then(value=>{setRows(value);setError('');return value}).catch(reason=>{setError(String(reason));return[]}),[])
  useEffect(()=>{void load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[load])
  const visibleRows=useMemo(()=>viewAll||!industry?rows:rows.filter(row=>row.folder===industry),[industry,rows,viewAll])
  useEffect(()=>setSelected(current=>visibleRows.find(row=>row.run_id===current?.run_id)||visibleRows[0]||null),[visibleRows])
  const loadOutput=useCallback(async()=>{if(!selected)return;setOutputError('');try{const value=await api<{output:string}>(`/jobs/${selected.run_id}/output`);setOutput(value.output)}catch(reason){setOutputError(String(reason))}},[selected])
  useEffect(()=>{void loadOutput()},[loadOutput])
  const cancel=async()=>{if(!selected||!confirm('取消这个任务？已写入的中间产物不会被静默删除。'))return;await api(`/jobs/${selected.run_id}/cancel`,{method:'POST'});await load()}
  const retry=async()=>{if(!selected)return;const result=await api<{run_id:string}>(`/jobs/${selected.run_id}/retry`,{method:'POST'});const next=await load();setSelected(next.find(row=>row.run_id===result.run_id)||null)}
  const destination=selected?jobDestination(selected):null
  return <><Header eyebrow="OPERATIONS" title="任务中心" body="查看任务正在做什么、是否成功，以及下一步去哪里。状态来自持久任务记录。" actions={<><div className="segmented compact"><button className={!viewAll?'active':''} onClick={()=>setViewAll(false)} disabled={!industry}>当前行业</button><button className={viewAll?'active':''} onClick={()=>setViewAll(true)}>全部行业</button></div><button className="button secondary" onClick={load}><RefreshCw/>刷新</button></>}/>
    {error?<Empty title="任务中心不可用" body={error}/>:<div className="reader-layout"><section className="section-card job-list">{!visibleRows.length?<Empty title="当前没有任务" body="从每日情报、研究产物或研究助手发起任务后会显示在这里。" compact/>:visibleRows.map(row=>{const status=row.stalled?'stalled':row.status;return <button key={row.run_id} className={selected?.run_id===row.run_id?'active':''} onClick={()=>setSelected(row)}><JobStatusIcon status={status}/><span><strong>{row.title}</strong><small>{row.folder||'行业未知'} · {originLabel(row.origin)} · {jobStageLabel(row.stage,row.operation)} · {progressLabel(row)}<br/>{row.updated_at} · {row.run_id.slice(0,12)}</small></span><em>{jobStatusLabel(status)}</em></button>})}</section>
      <section className="section-card log-view"><div className="section-title"><div><h2>{selected?.title||'选择一个任务'}</h2>{selected?.parent_run_id&&<p className="subtle">重试自 {selected.parent_run_id.slice(0,12)}</p>}</div><div className="section-actions">{selected&&canAction(selected,'cancel')&&<button className="button danger" onClick={()=>void cancel()}><Square/>取消</button>}{selected&&canAction(selected,'retry')&&<button className="button secondary" onClick={()=>void retry()}><RotateCcw/>{selected.status==='paused'?'恢复执行':'安全重试'}</button>}{selected?.artifact_path&&<a className="button secondary" href={artifactUrl(selected.artifact_path)} target="_blank" rel="noreferrer"><ExternalLink/>{selected.status==='partial'?'查看已保留内容':'打开产物'}</a>}{selected&&!selected.artifact_path&&destination&&['completed','partial'].includes(selected.status)&&<a className="button secondary" href={destination.href}><ExternalLink/>{selected.status==='partial'?'查看已保留内容':destination.label}</a>}{selected&&<span className={`status-pill ${selected.stalled?'stalled':selected.status}`}><JobStatusIcon status={selected.stalled?'stalled':selected.status}/>{jobStatusLabel(selected.stalled?'stalled':selected.status)}</span>}</div></div>
        {selected&&<><div className={`job-progress ${selected.progress_mode==='indeterminate'?'indeterminate':''}`}>{selected.progress_mode==='determinate'&&<span style={{width:`${Math.max(0,Math.min(100,selected.progress||0))}%`}}/>}</div><dl className="job-metadata"><dt>阶段</dt><dd>{jobStageLabel(selected.stage,selected.operation)} · {progressLabel(selected)}</dd><dt>已用时间</dt><dd>{selected.elapsed_seconds||0} 秒</dd><dt>结果类型</dt><dd>{resultLabel(selected.result_kind)}</dd><dt>来源</dt><dd>{originLabel(selected.origin)}</dd><dt>Provider / 模型</dt><dd>{selected.provider||'local'}{selected.model?` / ${selected.model}`:''}</dd><dt>时间窗口</dt><dd>{selected.time_window?.start&&selected.time_window.end?`${selected.time_window.start} → ${selected.time_window.end} · ${selected.time_window.timezone}`:'未声明'}</dd><dt>心跳</dt><dd>{selected.heartbeat_at||'尚无'}</dd><dt>错误原因</dt><dd>{jobErrorLabel(selected.error_category)||'无'}{selected.error?` · ${selected.error}`:''}</dd></dl></>}
        {outputError?<div className="inline-recovery"><div><strong>日志暂时无法读取</strong><p className="subtle">任务状态仍然可用。</p></div><button className="button secondary" onClick={()=>void loadOutput()}>重试读取日志</button></div>:<pre aria-live="polite">{selected?output||'暂无代表性日志。':'选择左侧任务查看阶段、进度、警告、产物路径和终态。'}</pre>}</section></div>}
  </>
}

function originLabel(origin:Job['origin']|undefined){return origin?({app:'App',manual:'手动',system_schedule:'系统调度',background_worker:'后台 Worker'} as const)[origin]:'App'}
function progressLabel(job:Job){return job.progress_mode==='indeterminate'?'进度暂不可估算':`${job.progress||0}%`}
function resultLabel(value:Job['result_kind']){return({artifact:'研究产物',local_data:'本地数据',task_package:'任务包（不是研究成品）',unknown:'待判断'} as const)[value||'unknown']}
function canAction(job:Job,action:'cancel'|'retry'){return job.recovery_actions?.includes(action)??(action==='cancel'?Boolean(job.active):['failed','partial','cancelled','interrupted'].includes(job.status))}
function JobStatusIcon({status}:{status:string}){const Icon=status==='completed'?CheckCircle2:status==='paused'||status==='cancelled'?CirclePause:status==='running'||status==='queued'?LoaderCircle:AlertTriangle;return <Icon className={status==='running'?'spin':''} aria-hidden="true"/>}
