import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, CirclePause, ExternalLink, LoaderCircle, RefreshCw, RotateCcw, Square } from 'lucide-react'
import { api, artifactUrl, type Job } from '../api'
import { Empty, Header } from './shared'

export default function JobsPage() {
  const [rows, setRows] = useState<Job[]>([]); const [selected, setSelected] = useState<Job | null>(null); const [output, setOutput] = useState(''); const [error, setError] = useState('')
  const load = useCallback(() => api<Job[]>('/jobs').then(value => { setRows(value);setSelected(current=>current?value.find(row=>row.run_id===current.run_id)||current:null);setError('');return value }).catch(e => {setError(String(e));return []}), [])
  useEffect(() => { void load(); const timer = setInterval(load, 3000); return () => clearInterval(timer) }, [load])
  useEffect(() => { if (selected) api<{ output: string }>(`/jobs/${selected.run_id}/output`).then(value => setOutput(value.output)) }, [selected, rows])
  const cancel = async () => { if (!selected || !confirm('取消这个任务？已写入的中间产物不会被静默删除。')) return; await api(`/jobs/${selected.run_id}/cancel`,{method:'POST'}); await load() }
  const retry = async () => { if (!selected) return; const result=await api<{run_id:string}>(`/jobs/${selected.run_id}/retry`,{method:'POST'}); const next=await load(); setSelected(next.find(row=>row.run_id===result.run_id)||null) }
  return <><Header eyebrow="OPERATIONS" title="任务中心" body="状态以持久化任务记录为准；运行、停滞、失败、部分完成和取消不会互相覆盖。" actions={<button className="button secondary" onClick={load}><RefreshCw/>刷新</button>}/>
    {error ? <Empty title="任务中心不可用" body={error}/> : <div className="reader-layout"><section className="section-card job-list">{rows.map(row => { const status = row.stalled ? 'stalled' : row.status; return <button key={row.run_id} className={selected?.run_id === row.run_id ? 'active' : ''} onClick={() => setSelected(row)}><JobStatusIcon status={status}/><span><strong>{row.title}</strong><small>{originLabel(row.origin)} · {row.stage||'等待阶段信息'} · {row.progress||0}%<br/>{row.updated_at} · {row.run_id.slice(0,12)}</small></span><em>{status}</em></button> })}</section><section className="section-card log-view"><div className="section-title"><div><h2>{selected?.title || '选择一个任务'}</h2>{selected?.parent_run_id&&<p className="subtle">重试自 {selected.parent_run_id.slice(0,12)}</p>}</div><div className="section-actions">{selected&&canAction(selected,'cancel')&&<button className="button danger" onClick={()=>void cancel()}><Square/>取消</button>}{selected&&canAction(selected,'retry')&&<button className="button secondary" onClick={()=>void retry()}><RotateCcw/>{selected.status==='paused'?'恢复执行':'安全重试'}</button>}{selected?.artifact_path&&<a className="button secondary" href={artifactUrl(selected.artifact_path)} target="_blank" rel="noreferrer"><ExternalLink/>打开产物</a>}{selected&&<span className={`status-pill ${selected.stalled ? 'stalled' : selected.status}`}><JobStatusIcon status={selected.stalled?'stalled':selected.status}/>{selected.stalled ? 'stalled' : selected.status}</span>}</div></div>{selected&&<><div className="job-progress"><span style={{width:`${Math.max(0,Math.min(100,selected.progress||0))}%`}}/></div><dl className="job-metadata"><dt>阶段</dt><dd>{selected.stage||'尚无阶段信息'} · {selected.progress||0}%</dd><dt>来源</dt><dd>{originLabel(selected.origin)}</dd><dt>Provider / 模型</dt><dd>{selected.provider||'local'}{selected.model?` / ${selected.model}`:''}</dd><dt>时间窗口</dt><dd>{selected.time_window?.start&&selected.time_window.end?`${selected.time_window.start} → ${selected.time_window.end} · ${selected.time_window.timezone}`:'未声明'}</dd><dt>心跳</dt><dd>{selected.heartbeat_at||'尚无'}</dd><dt>错误分类</dt><dd>{selected.error_category||'无'}{selected.error?` · ${selected.error}`:''}</dd></dl></>}<pre aria-live="polite">{selected ? output || '暂无代表性日志。' : '选择左侧任务查看阶段、进度、警告、产物路径和终态。'}</pre></section></div>}
  </>
}

function originLabel(origin:Job['origin']|undefined) { return origin?({app:'App',manual:'手动',system_schedule:'系统调度',background_worker:'后台 Worker'} as const)[origin]:'App' }
function canAction(job:Job,action:'cancel'|'retry') { return job.recovery_actions?.includes(action)??(action==='cancel'?Boolean(job.active):['failed','partial','cancelled','interrupted'].includes(job.status)) }
function JobStatusIcon({status}:{status:string}) { const Icon=status==='completed'?CheckCircle2:status==='paused'||status==='cancelled'?CirclePause:status==='running'||status==='queued'?LoaderCircle:AlertTriangle;return <Icon className={status==='running'?'spin':''} aria-hidden="true"/> }
