import { Search, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { api, type KnowledgeEntityDetail, type KnowledgeEntityPage, type OverviewPayload } from '../api'
import { ChainGraph, Empty, Header, Loading } from './shared'

export default function KnowledgePage({industry}:{industry:string}) {
  const [overview,setOverview]=useState<OverviewPayload|null>(null);const [page,setPage]=useState<KnowledgeEntityPage|null>(null);const [active,setActive]=useState<KnowledgeEntityDetail|null>(null);const [query,setQuery]=useState('');const [kind,setKind]=useState('');const [country,setCountry]=useState('');const [status,setStatus]=useState('');const [chain,setChain]=useState('');const [error,setError]=useState('')
  useEffect(()=>{setOverview(null);setActive(null);setError('');api<OverviewPayload>(`/industries/${industry}/overview`).then(value=>{setOverview(value);setError('')}).catch(reason=>setError(String(reason)))},[industry])
  const load=useCallback((offset=0)=>{const params=new URLSearchParams({limit:'50',offset:String(offset),...(query&&{query}),...(kind&&{kind}),...(country&&{country}),...(status&&{status}),...(chain&&{chain})});api<KnowledgeEntityPage>(`/industries/${industry}/knowledge/entities?${params}`).then(value=>{setPage(value);setError('')}).catch(reason=>setError(String(reason)))},[industry,query,kind,country,status,chain])
  useEffect(()=>{void load()},[load])
  const open=async(id:string)=>setActive(await api<KnowledgeEntityDetail>(`/industries/${industry}/knowledge/entities/${id}`))
  if(error)return <Empty title="知识结构不可用" body={error}/>
  if(!overview||!page)return <Loading label="正在载入知识结构与实体…"/>
  return <><Header eyebrow="KNOWLEDGE GRAPH" title="知识结构" body="按产业链端点、实体类别、地区和事实状态浏览；详情保留角色、关系、时间与证据。"/>
    <section className="section-card chain-section"><div className="section-title"><div><h2>产业链有向图</h2><p className="subtle">仅显示已持久化关系；没有边时不会根据列表顺序猜测上下游。</p></div><span>{overview.chain.length} 节点 · {overview.chain_edges.length} 边</span></div><ChainGraph nodes={overview.chain} edges={overview.chain_edges}/></section>
    <section className="section-card knowledge-explorer"><div className="toolbar entity-toolbar"><label className="search-field"><span className="sr-only">搜索实体</span><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索名称、英文名或别名"/></label><label className="compact-field"><span>类型</span><select value={kind} onChange={event=>setKind(event.target.value)}><option value="">全部</option>{['company','research_group','government_institution','association','investment_institution','person','product','technology','standard','policy'].map(value=><option key={value}>{value}</option>)}</select></label><label className="compact-field"><span>地区</span><input value={country} onChange={event=>setCountry(event.target.value)} placeholder="CN / US / …"/></label><label className="compact-field"><span>状态</span><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">全部</option><option value="accepted">accepted</option><option value="candidate">candidate</option><option value="manual_review">manual_review</option></select></label><label className="compact-field"><span>产业链</span><select value={chain} onChange={event=>setChain(event.target.value)}><option value="">全部</option>{overview.chain.map(node=><option key={node.id||node.name}>{node.name}</option>)}</select></label></div>
      {!page.items.length?<Empty title="当前筛选没有实体" body="更改筛选条件或运行覆盖搜索。" compact/>:<ul className="knowledge-table">{page.items.map(entity=><li key={`${entity.id}:${entity.chain||''}`}><button onClick={()=>void open(entity.id)}><span className="avatar">{entity.name.slice(0,1)}</span><div><strong>{entity.name}</strong><small>{entity.name_en||'无英文名'} · {entity.kind} · {entity.country||'地区未知'}</small></div><span>{entity.chain||entity.role||'待分类'}</span><em className={`status-pill ${entity.status}`}>{entity.status}</em></button></li>)}</ul>}
      <div className="pager"><button className="button secondary" disabled={!page.offset} onClick={()=>load(Math.max(0,page.offset-page.limit))}>上一页</button><span>{page.total?`${page.offset+1}–${Math.min(page.offset+page.items.length,page.total)} / ${page.total}`:'0 / 0'}</span><button className="button secondary" disabled={page.next_offset==null} onClick={()=>load(page.next_offset||0)}>下一页</button></div>
    </section>
    {active&&<div className="entity-drawer" role="dialog" aria-modal="true" aria-labelledby="knowledge-entity-title"><button className="drawer-backdrop" aria-label="关闭实体详情" onClick={()=>setActive(null)}/><aside><button className="icon-button drawer-close" aria-label="关闭实体详情" autoFocus onClick={()=>setActive(null)}><X/></button><span className="eyebrow">{active.kind} · {active.status}</span><h2 id="knowledge-entity-title">{active.canonical_name}</h2><p>{active.name_en||''} · {active.country||'地区未知'}</p><h3>产业链角色</h3>{active.roles.map((role,index)=><article className="claim-card" key={`${role.chain}:${role.role}:${index}`}><strong>{role.chain} · {role.role}</strong><span className="tag">{role.status}</span><p>{role.evidence_count} 条证据{role.valid_from?` · ${role.valid_from} → ${role.valid_to||'至今'}`:''}</p></article>)}<h3>关系</h3>{active.relations.map(row=><article className="relation-row" key={row.id}><strong>{row.src_name}</strong><span>{row.predicate} →</span><strong>{row.dst_name}</strong></article>)}<h3>断言与证据</h3>{active.claims.map(claim=><article className="claim-card" key={claim.id}><strong>{claim.predicate}</strong><span className="tag">{claim.status}</span><pre>{JSON.stringify(claim.object,null,2)}</pre>{claim.evidence.map((item,index)=>item.document_url?<a key={index} href={item.document_url} target="_blank" rel="noreferrer">{item.relation} · {item.document_title||'证据文档'}</a>:null)}</article>)}</aside></div>}
  </>
}
