import { useCallback, useEffect, useState } from 'react'
import { ExternalLink, Globe2, Trash2, X } from 'lucide-react'
import { api, type SourceItem, type SourcesPayload } from '../api'
import { Empty, Header, Loading, type Toast } from './shared'
import SourceCampaignPanel from './sources/SourceCampaignPanel'

const categoryLabels:Record<string,string>={official:'政府、监管与标准',associations:'行业协会',blogs:'机构与企业博客',platforms:'专业平台',self_media:'专业作者与自媒体',news:'新闻媒体',journals:'学术期刊与论文',financials:'公司披露',finance:'金融与市场数据'}
const statusLabels:Record<string,string>={active:'正在监控',recommended_manual:'建议人工阅读',manual:'建议人工阅读',reserve:'备用',quarantined:'待复核',rejected:'不采用'}

export default function SourcesPage({ industry, notify }: { industry: string; notify: (t: Toast) => void }) {
  const [data, setData] = useState<SourcesPayload | null>(null); const [filter, setFilter] = useState(''); const [status, setStatus] = useState(''); const [adding, setAdding] = useState(false); const [error, setError] = useState(''); const [reviewReasons,setReviewReasons]=useState<Record<string,string>>({})
  const load = useCallback(() => { setData(null); setError(''); api<SourcesPayload>(`/industries/${industry}/sources`).then(setData).catch(e => { setError(String(e)); notify({kind:'error',text:String(e)}) }) }, [industry, notify])
  useEffect(() => { load() }, [load])
  if (error) return <Empty title="信息源不可用" body={error}/>
  const categories = data?.categories || {}; const allRows = Object.entries(categories).flatMap(([category, values]) => values.map(value => ({...value, category}))); const rows = allRows.filter(row => (!filter || row.category === filter) && (!status || (row.monitoring_status || 'active') === status)); const statusCounts = allRows.reduce<Record<string, number>>((counts, row) => { const key=row.monitoring_status || 'active'; counts[key]=(counts[key]||0)+1; return counts }, {})
  const add = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values=Object.fromEntries(new FormData(event.currentTarget)); try { await api(`/industries/${industry}/sources`,{method:'POST',body:JSON.stringify(values)}); notify({kind:'ok',text:'信息源已加入当前行业'}); setAdding(false); load() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const remove = async (source: SourceItem) => { if(!confirm(`移除信息源“${source.name}”？可在审计记录中追溯。`)) return; const params=new URLSearchParams({category:source.category,url:source.url}); await api(`/industries/${industry}/sources?${params}`,{method:'DELETE'}); notify({kind:'ok',text:'信息源已移除'}); load() }
  const reassess=async(source:SourceItem,decision:'active'|'manual'|'reserve'|'rejected')=>{const sourceId=source.id||'';const reason=(reviewReasons[sourceId]||'').trim();if(!sourceId||!reason){notify({kind:'error',text:'重新评估前请填写说明'});return}try{await api(`/industries/${industry}/sources/${sourceId}/reassess`,{method:'POST',body:JSON.stringify({decision,actor:'local-user',reason})});notify({kind:'ok',text:`${source.name} 已重新评估为 ${decision}`});load()}catch(e){notify({kind:'error',text:String(e)})}}
  return <><Header eyebrow="SOURCES" title="信息源" body="这里保存系统知道的全部来源。常用来源会自动监控；需要登录或无法稳定抓取的优质来源仍会保留，并提示你人工阅读。" actions={<button className="button primary" onClick={() => setAdding(!adding)}>{adding ? <X/> : <Globe2/>}{adding ? '取消添加' : '手动添加'}</button>}/>
    {adding && <form className="inline-form section-card" onSubmit={add}><label><span>来源类别</span><select name="category" required>{Object.entries(categoryLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>来源名称</span><input name="name" required/></label><label><span>来源网址</span><input name="url" type="url" required placeholder="https://…"/></label><label><span>为什么值得关注</span><input name="note"/></label><button className="button primary">保存来源</button></form>}
    <div className="toolbar"><label className="compact-field"><span>来源类别</span><select value={filter} onChange={e => setFilter(e.target.value)}><option value="">全部类别</option>{Object.keys(categories).map(name => <option key={name} value={name}>{categoryLabels[name]||name}</option>)}</select></label><label className="compact-field"><span>使用状态</span><select value={status} onChange={e => setStatus(e.target.value)}><option value="">全部状态</option>{['active','recommended_manual','reserve','quarantined'].map(name => <option key={name} value={name}>{statusLabels[name]||name} · {statusCounts[name] || 0}</option>)}</select></label><span className="toolbar-note">显示 {rows.length} 个 · 共保存 {allRows.length} 个</span></div>
    <section className="source-grid">{!data ? <Loading label="正在检查信息源…"/> : rows.map(source => <article className="source-card" key={`${source.category}-${source.url}`}><span className="source-type">{categoryLabels[source.category]||source.category}</span><span className={`health health-${source.monitoring_status || 'active'}`} title={source.governance_reason || ''}>{statusLabels[source.monitoring_status||'active']||source.monitoring_status}</span><h3>{source.name}</h3><p>{source.note || source.selection_reason || '尚未补充推荐理由'}</p>{source.health&&<small className="health-detail">{source.health.status==='fresh'?'最近检查正常':`当前无法自动获取 · 最近成功 ${source.health.last_good_at||'暂无记录'}`}</small>}<div><span>{source.tier==='primary'?'一手来源':'代表性来源'}</span><span>{source.publisher_country || source.origin || '地区未知'}</span><a href={source.url} target="_blank" rel="noreferrer" aria-label="打开来源"><ExternalLink/></a><button onClick={() => remove(source)} aria-label="移除来源"><Trash2/></button></div>{source.id&&<details className="source-reassessment"><summary>更改使用状态</summary><label><span>更改理由</span><textarea value={reviewReasons[source.id]||''} onChange={event=>setReviewReasons(current=>({...current,[source.id!]:event.target.value}))}/></label><div className="candidate-actions">{(['active','manual','reserve','rejected'] as const).map(value=><button className="button secondary" key={value} onClick={()=>void reassess(source,value)}>{statusLabels[value]||value}</button>)}</div></details>}</article>)}</section>
    <SourceCampaignPanel industry={industry} notify={notify}/>
  </>
}
