import { useCallback, useEffect, useState } from 'react'
import { Activity, Clock3, Database, FolderKanban, RefreshCw, RotateCcw, type LucideIcon } from 'lucide-react'
import { api, artifactUrl, type AuditRow, type AutomationPayload, type BackgroundPayload, type HealthPayload, type IndustryBundle, type IndustryImportResult, type RestorePreview, type Schedule, type SetupPayload, type TrashItem } from '../api'
import { ConfirmDialog, Empty, Header, RunFeedback, type Toast } from './shared'
import WorkflowSettingsPanel from './settings/WorkflowSettingsPanel'

const actionLabels: Record<string,string> = {daily:'每日采集',weekly:'每周产物',monthly:'每月产物',quarterly:'季度产物'}
const INDUSTRY_BUNDLE_MAX_BYTES=64*1024*1024
type PendingConfirm={title:string;body:string;label:string;returnFocus:HTMLElement;action:()=>Promise<void>|void}

export default function SystemPage({ industry, notify, setup=null }: { industry: string; notify: (t: Toast) => void; setup?: SetupPayload|null }) {
  const [health, setHealth] = useState<HealthPayload | null>(null); const [automation, setAutomation] = useState<AutomationPayload|null>(null); const [background,setBackground]=useState<BackgroundPayload|null>(null); const [trash, setTrash] = useState<TrashItem[]>([]); const [audits, setAudits] = useState<AuditRow[]>([]); const [drift,setDrift]=useState<{metrics:Array<{metric:string;window_days:7|30;status:string;value:number|null;diagnosis:string}>;alert_count:number}|null>(null);const [error, setError] = useState('');const [stopped,setStopped]=useState(false)
  const [pendingConfirm,setPendingConfirm]=useState<PendingConfirm|null>(null)
  const [runId,setRunId]=useState('')
  const load = useCallback(() => Promise.all([api<HealthPayload>('/health'),api<{items:TrashItem[]}>('/trash'),api<AuditRow[]>('/trash/audits/recent'),industry?api<AutomationPayload>(`/industries/${industry}/automation`):Promise.resolve(null),api<BackgroundPayload>('/background'),industry?Promise.resolve().then(()=>api<{metrics:Array<{metric:string;window_days:7|30;status:string;value:number|null;diagnosis:string}>;alert_count:number}>(`/industries/${industry}/quality-drift`)).catch(()=>null):Promise.resolve(null)]).then(([h,t,u,a,b,d])=>{setHealth(h);setTrash(t.items);setAudits(u);setAutomation(a);setBackground(b);setDrift(d);setError('')}).catch(e => setError(String(e))), [industry])
  useEffect(() => { void load(); const timer = setInterval(load, 5000); return () => clearInterval(timer) }, [load])
  const shutdown = async () => { await api('/shutdown', {method:'POST'});if(window.intdogDesktop)await window.intdogDesktop.close();else setStopped(true) }
  const createIndustry = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values=Object.fromEntries(new FormData(event.currentTarget)); try { await api('/industries',{method:'POST',body:JSON.stringify(values)}); location.reload() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const renameIndustry = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values=Object.fromEntries(new FormData(event.currentTarget)); try { await api(`/industries/${industry}`,{method:'PATCH',body:JSON.stringify(values)}); localStorage.setItem('intdog.industry',String(values.folder)); location.reload() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const archiveIndustry = async () => { try { await api(`/industries/${industry}`,{method:'DELETE'}); localStorage.removeItem('intdog.industry'); location.reload() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const exportIndustry = async () => { try { const bundle=await api<IndustryBundle>(`/industries/${industry}/export`); const url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'})); const link=document.createElement('a');link.href=url;link.download=`intdog-${industry}-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);notify({kind:'ok',text:'行业包已导出；不包含凭据和本机路径'}) } catch(e) { notify({kind:'error',text:String(e)}) } }
  const importIndustry = async (event:React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values=new FormData(event.currentTarget); const file=values.get('bundle'); if(!(file instanceof File)||!file.size){notify({kind:'error',text:'请选择 IntDog 行业包 JSON'});return} if(file.size>INDUSTRY_BUNDLE_MAX_BYTES){notify({kind:'error',text:'行业包超过 64 MiB 上限'});return} try { const bundle=JSON.parse(await file.text()) as IndustryBundle; const result=await api<IndustryImportResult>('/industries/import',{method:'POST',body:JSON.stringify({folder:String(values.get('folder')||''),name:String(values.get('name')||''),bundle})});localStorage.setItem('intdog.industry',result.folder);notify({kind:'ok',text:`已导入 ${result.name}`});location.reload() } catch(e) { notify({kind:'error',text:`导入失败：${String(e)}`}) } }
  const configure = async (schedule:Schedule, changes:Partial<Schedule>) => { const next={...schedule,...changes}; try { await api(`/industries/${industry}/automation/${schedule.action}`,{method:'PUT',body:JSON.stringify(next)}); notify({kind:'ok',text:`${actionLabels[schedule.action]}调度已更新（不发送邮件）`}); await load() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const runNow = async (action:string) => { const result=await api<{run_id:string}>(`/industries/${industry}/automation/${action}/run`,{method:'POST'});setRunId(result.run_id);notify({kind:'ok',text:`${actionLabels[action]}已进入任务队列`}) }
  const setBackgroundService=async(enabled:boolean)=>{const desktop=window.intdogDesktop;if(!desktop){notify({kind:'error',text:'当前不是已安装的 Desktop 运行时'});return}try{if(enabled){const approval=await desktop.requestBackgroundInstall();await desktop.installBackground({intervalMinutes:15,nonce:approval.nonce})}else await desktop.removeBackground();notify({kind:'ok',text:enabled?'已启用系统后台唤醒':'已停用系统后台唤醒'});await load()}catch(e){notify({kind:'error',text:String(e)})}}
  const setBackgroundPermission=async(item:BackgroundPayload['permissions'][number],allowed:boolean)=>{try{await api('/background/permissions',{method:'PUT',body:JSON.stringify({folder:item.folder,provider:item.provider,operation:item.operation,allowed,reason:allowed?'User granted background execution':'User revoked background execution'})});notify({kind:'ok',text:allowed?'已授予后台 Provider 权限':'已撤销后台 Provider 权限'});await load()}catch(e){notify({kind:'error',text:String(e)})}}
  const requestRestore = async (item:TrashItem,returnFocus:HTMLElement) => { try { const preview=await api<RestorePreview>(`/trash/${encodeURIComponent(item.id)}/preview`); if(!preview.restorable){notify({kind:'error',text:'该记录当前不可恢复'});return} const collision=preview.collisions.length?` 冲突：${preview.collisions.join('；')}`:'';setPendingConfirm({title:`恢复“${item.name}”`,body:`预计恢复 ${preview.restore_count} 项，跳过 ${preview.skip_count} 项。${collision}`,label:'确认恢复',returnFocus,action:async()=>{const result=await api<{restored:number;skipped:number}>(`/trash/${encodeURIComponent(item.id)}/restore`,{method:'POST',body:JSON.stringify({desired_folder:''})});notify({kind:'ok',text:`已恢复 ${result.restored} 项，跳过 ${result.skipped} 项`});if(item.kind==='industry')location.reload();else await load()}})} catch(e) { notify({kind:'error',text:String(e)}) } }
  const confirmPending=async()=>{const pending=pendingConfirm;if(!pending)return;setPendingConfirm(null);try{await pending.action()}catch(e){notify({kind:'error',text:String(e)})}}
  if(stopped)return <div className="shutdown-state" role="status" tabIndex={-1}><Database/><h1>IntDog 已安全退出</h1><p>本地服务已停止。现在可以关闭窗口；重新打开快捷方式即可恢复工作区。</p></div>
  return <><Header eyebrow="SYSTEM" title="系统状态" body="默认 Web 服务拥有持久调度、任务与恢复状态。所有自动任务只采集和生成产物，不发送邮件。" actions={<><button className="button secondary" onClick={()=>void load()}><RefreshCw/>刷新</button> <button className="button danger" onClick={event=>setPendingConfirm({title:'安全退出 IntDog',body:'将停止本地服务；运行中的前台任务也会结束。后台计划仍按已授权设置运行。',label:'退出并停止',returnFocus:event.currentTarget,action:shutdown})}>退出 IntDog</button></>}/>
    <nav className="page-nav" aria-label="系统页面导航"><a href="#system-health">运行状态</a><a href="#workflow-settings">智能体设置</a><a href="#system-quality">质量</a><a href="#system-automation">自动化</a><a href="#industry-manager">行业管理</a><a href="#system-trash">回收站</a></nav>
    <div className="system-grid" id="system-health"><StatusCard icon={Activity} label="本地 API" value={error ? '不可用' : health?.status || '检查中'} ok={!error && health?.status === 'ready'}/><StatusCard icon={Database} label="知识数据库" value={health?.database ? '已连接' : '等待初始化'} ok={Boolean(health?.database)}/><StatusCard icon={FolderKanban} label="活动任务" value={String(health?.active_jobs ?? '—')} ok={true}/><StatusCard icon={Clock3} label="自动调度" value={health?.automation_running?'运行中':'等待服务'} ok={Boolean(health?.automation_running)}/></div>
    <WorkflowSettingsPanel industry={industry} setup={setup} notify={notify}/>
    <section className="section-card drift-panel" id="system-quality"><div className="section-title"><div><h2>情报系统质量</h2><p className="subtle">只有相对稳定基线出现显著变化时才提示漂移。</p></div><span className={`status-pill ${drift?.alert_count?'failed':'completed'}`}>{drift?.alert_count?`${drift.alert_count} 个漂移告警`:'未发现漂移'}</span></div>{!drift?.metrics.length?<Empty title="尚无质量观测" body="积累来源、分类和固定评估集观测后再判断趋势。" compact/>:<><p className="subtle">{drift.metrics.every(item=>item.status==='insufficient_data')?'数据不足以判断趋势；首次采集属于基线建立，不是漂移。':'已比较 7 日与 30 日窗口；算法版本变化不会计为数据漂移。'}</p><details><summary>查看完整质量指标</summary><div className="drift-grid">{([7,30] as const).map(window=><article key={window}><h3>{window} 日</h3>{drift.metrics.filter(item=>item.window_days===window).map(item=><p key={`${window}:${item.metric}`}><strong>{item.metric}</strong><span>{item.value??'N/A'} · {item.status}</span><small>{item.diagnosis}</small></p>)}</article>)}</div></details></>}</section>
    <section className="section-card background-panel" id="system-automation"><div className="section-title"><div><h2>系统后台运行</h2><p className="subtle">关闭窗口后由操作系统唤醒一次性 Worker；同一周期仍只能被一个运行时领取。</p></div><span className={`status-pill ${background?.service.enabled?'completed':'paused'}`}>{background?.service.enabled?'已启用':'未启用'}</span></div><div className="two-columns"><div><dl><dt>服务</dt><dd>{background?.service.platform||'不可用'} · {background?.service.installed?'已安装':'未安装'}</dd><dt>下次运行</dt><dd>{background?.next_run_at||'尚无到期计划'}</dd><dt>最近唤醒</dt><dd><span>最近唤醒：{background?.last_wakeup?.status||'尚无'}</span>{background?.last_wakeup?.started_at?` · ${background.last_wakeup.started_at}`:''}</dd><dt>错误</dt><dd>{background?.service.error_category||background?.schedule_errors[0]?.pause_reason||'无'}</dd></dl><div className="section-actions">{background?.service.enabled?<button className="button danger" onClick={()=>void setBackgroundService(false)} disabled={!window.intdogDesktop}>停用后台运行</button>:<button className="button primary" onClick={()=>void setBackgroundService(true)} disabled={!window.intdogDesktop}>启用后台运行</button>}</div></div><div><h3>后台 Provider 权限</h3>{background?.permissions.length?<div className="audit-list background-permissions">{background.permissions.map(item=><article key={`${item.folder}:${item.provider}:${item.operation}`}><strong>{item.provider} · {item.operation}</strong><span>{item.folder} · {item.allowed?'已授权':'未授权'} · {item.updated_at}</span><button className={`button ${item.allowed?'danger':'secondary'}`} onClick={()=>void setBackgroundPermission(item,!item.allowed)}>{item.allowed?'撤销':'授权'}</button></article>)}</div>:<p className="subtle">未配置付费 Provider 后台计划；公开来源任务不需要凭据授权。</p>}</div></div></section>
    <section className="section-card automation-panel"><div className="section-title"><div><h2>自动化计划</h2><p className="subtle">只有成功任务才推进周期；失败会指数退避并保留尝试周期、任务与错误。邮件推送已禁用。</p></div><span className="status-pill">NO EMAIL</span></div>{!industry?<Empty title="暂无当前行业" body="创建行业后即可配置自动化。" compact/>:<div className="schedule-grid">{(automation?.schedules||[]).map(schedule=><article key={schedule.action}><div><strong>{actionLabels[schedule.action]} <span className={`status-pill ${schedule.runtime_status}`}>{schedule.runtime_status}</span></strong><small>下次：{schedule.next_run_at||'待计算'}<br/>最近成功：{schedule.last_success_at||'尚未运行'}{schedule.retry_count?` · 重试 ${schedule.retry_count}`:''}<br/>来源：{schedule.last_origin||'尚未执行'}{schedule.last_window_start?` · ${schedule.last_window_start} → ${schedule.last_window_end||'—'} · ${schedule.last_window_timezone||schedule.timezone}`:''}</small></div><label className="switch"><input type="checkbox" checked={schedule.enabled} onChange={e=>void configure(schedule,{enabled:e.target.checked})}/><span/>启用</label><label><span>本地时间</span><input type="time" value={schedule.local_time} onChange={e=>void configure(schedule,{local_time:e.target.value})}/></label>{schedule.action!=='daily'&&<><label><span>流水线</span><select value={schedule.pipeline_mode} onChange={e=>void configure(schedule,{pipeline_mode:e.target.value as Schedule['pipeline_mode']})}><option value="generate">采集并生成报告</option><option value="aggregate">仅聚合已有情报</option></select></label><label><span>智能体</span><select value={schedule.provider} onChange={e=>void configure(schedule,{provider:e.target.value})}><option value="">继承全局 / 行业默认</option>{setup?.agents.filter(item=>item.schedulable).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}{setup?.api_providers.filter(item=>item.schedulable).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></>}<button className="button secondary" onClick={()=>void runNow(schedule.action)}>立即运行</button>{schedule.last_artifact_path&&<a className="button secondary" href={artifactUrl(schedule.last_artifact_path)} target="_blank" rel="noreferrer">打开最近产物</a>}{(schedule.last_error||schedule.pause_reason)&&<p className="field-error">{schedule.last_error||schedule.pause_reason}{schedule.retry_after&&<> · 下次重试 {schedule.retry_after}</>}</p>}</article>)}</div>}<RunFeedback runId={runId} onTerminal={()=>void load()}/></section>
    <section className="section-card system-detail"><h2>数据与信任边界</h2><dl><dt>数据目录</dt><dd>{health?.data_root || '正在读取'}</dd><dt>网络服务</dt><dd>仅监听 127.0.0.1，并验证 Host、Origin 与启动会话</dd><dt>会话保护</dt><dd>{health?.session_required?'已启用':'开发模式未注入会话凭证'}</dd><dt>实时状态</dt><dd>浏览器读取权威任务记录；空闲不等于停滞</dd></dl></section>
    <section className="section-card industry-manager" id="industry-manager"><div className="section-title"><div><h2>行业管理</h2><p className="subtle">创建、调整或迁移独立的本地行业工作区。当前行业：{industry||'未选择'}</p></div></div><div className="industry-manager-grid"><div className="manager-block"><header><span>01</span><div><h3>当前行业</h3><p>修改显示名称或数据文件夹。</p></div></header><form onSubmit={renameIndustry}><label><span>显示名称</span><input name="name" disabled={!industry}/></label><label><span>数据文件夹</span><input name="folder" defaultValue={industry} disabled={!industry} required/></label><button className="button secondary" disabled={!industry}>保存修改</button></form><button className="button danger manager-danger" disabled={!industry} onClick={event=>setPendingConfirm({title:`归档行业“${industry}”`,body:'数据会移入可恢复的回收站，不会永久删除。',label:'确认归档',returnFocus:event.currentTarget,action:archiveIndustry})}>归档当前行业</button></div><div className="manager-block"><header><span>02</span><div><h3>新建行业</h3><p>建立一个空白的独立研究空间。</p></div></header><form onSubmit={createIndustry}><label><span>行业名称</span><input name="name" required/></label><label><span>数据文件夹</span><input name="folder" required/></label><button className="button primary">新建行业</button></form></div><div className="manager-block"><header><span>03</span><div><h3>导入与导出</h3><p>迁移不含凭据的本地行业包。</p></div></header><button className="button secondary" type="button" disabled={!industry} onClick={()=>void exportIndustry()}>导出当前行业</button><form onSubmit={importIndustry}><label><span>导入行业名称</span><input name="name" required/></label><label><span>数据文件夹</span><input name="folder" required/></label><label><span>行业包 JSON</span><input name="bundle" type="file" accept="application/json,.json" aria-label="导入行业包" required/></label><button className="button secondary">导入行业包</button></form></div></div></section>
    <section className="section-card trash-panel" id="system-trash"><div className="section-title"><div><h2>回收站</h2><p className="subtle">恢复优先；本轮不提供不可逆永久删除。</p></div><span>{trash.length} 条记录</span></div>{!trash.length?<Empty title="回收站为空" body="归档行业或删除每日情报后，可在这里恢复。" compact/>:<div className="trash-list">{trash.map(item=><article key={item.id}><span className="trash-kind">{item.kind==='industry'?'行业':'每日情报'}</span><div><strong>{item.name}</strong><small>{item.created_at||'时间未知'} · {item.item_count} 项 · {item.id}</small></div><button className="button secondary" onClick={event=>void requestRestore(item,event.currentTarget)}><RotateCcw/>恢复</button></article>)}</div>}</section>
    <section className="section-card audit-panel"><div className="section-title"><div><h2>最近审计记录</h2><p className="subtle">重要写操作、人工纠正与恢复均保留主体、对象和时间。</p></div><span>{audits.length} 条</span></div>{!audits.length?<Empty title="暂无审计记录" body="执行行业、Story 或恢复操作后会出现在这里。" compact/>:<div className="audit-list">{audits.slice(0,30).map(row=><article key={row.id}><time>{row.occurred_at}</time><strong>{row.action}</strong><span>{row.actor} · {row.object_type}{row.object_id?` · ${row.object_id}`:''}</span></article>)}</div>}</section>
    <ConfirmDialog open={Boolean(pendingConfirm)} title={pendingConfirm?.title||''} body={pendingConfirm?.body||''} confirmLabel={pendingConfirm?.label} danger returnFocus={pendingConfirm?.returnFocus} onCancel={()=>setPendingConfirm(null)} onConfirm={()=>void confirmPending()}/>
  </>
}

function StatusCard({ icon: Icon, label, value, ok }: { icon: LucideIcon; label: string; value: string; ok: boolean }) { return <div className="status-card"><span><Icon/></span><div><small>{label}</small><strong>{value}</strong></div><i className={ok ? 'ok' : 'warn'}/></div> }
