import { useCallback, useEffect, useState } from 'react'
import { Activity, Clock3, Database, FolderKanban, RefreshCw, RotateCcw, type LucideIcon } from 'lucide-react'
import { api, artifactUrl, type AuditRow, type AutomationPayload, type HealthPayload, type RestorePreview, type Schedule, type TrashItem } from '../api'
import { Empty, Header, type Toast } from './shared'

const actionLabels: Record<string,string> = {daily:'每日采集',weekly:'每周产物',monthly:'每月产物',quarterly:'季度产物'}

export default function SystemPage({ industry, notify }: { industry: string; notify: (t: Toast) => void }) {
  const [health, setHealth] = useState<HealthPayload | null>(null); const [automation, setAutomation] = useState<AutomationPayload|null>(null); const [trash, setTrash] = useState<TrashItem[]>([]); const [audits, setAudits] = useState<AuditRow[]>([]); const [error, setError] = useState('')
  const load = useCallback(() => Promise.all([api<HealthPayload>('/health'),api<{items:TrashItem[]}>('/trash'),api<AuditRow[]>('/trash/audits/recent'),industry?api<AutomationPayload>(`/industries/${industry}/automation`):Promise.resolve(null)]).then(([h,t,u,a])=>{setHealth(h);setTrash(t.items);setAudits(u);setAutomation(a);setError('')}).catch(e => setError(String(e))), [industry])
  useEffect(() => { void load(); const timer = setInterval(load, 5000); return () => clearInterval(timer) }, [load])
  const shutdown = async () => { if (!confirm('退出 IntDog 并停止本地服务？运行中的任务也会随服务结束。')) return; await api('/shutdown', {method:'POST'}); document.body.innerHTML='<div class="empty"><h2>IntDog 已退出</h2><p>现在可以关闭此窗口。</p></div>' }
  const createIndustry = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values=Object.fromEntries(new FormData(event.currentTarget)); try { await api('/industries',{method:'POST',body:JSON.stringify(values)}); location.reload() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const renameIndustry = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values=Object.fromEntries(new FormData(event.currentTarget)); try { await api(`/industries/${industry}`,{method:'PATCH',body:JSON.stringify(values)}); localStorage.setItem('intdog.industry',String(values.folder)); location.reload() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const archiveIndustry = async () => { if(!confirm(`归档行业“${industry}”？数据会移入可恢复的回收站。`)) return; try { await api(`/industries/${industry}`,{method:'DELETE'}); localStorage.removeItem('intdog.industry'); location.reload() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const configure = async (schedule:Schedule, changes:Partial<Schedule>) => { const next={...schedule,...changes}; try { await api(`/industries/${industry}/automation/${schedule.action}`,{method:'PUT',body:JSON.stringify(next)}); notify({kind:'ok',text:`${actionLabels[schedule.action]}调度已更新（不发送邮件）`}); await load() } catch(e) { notify({kind:'error',text:String(e)}) } }
  const runNow = async (action:string) => { await api(`/industries/${industry}/automation/${action}/run`,{method:'POST'}); notify({kind:'ok',text:`${actionLabels[action]}已进入任务队列`}); location.hash='/jobs' }
  const restore = async (item:TrashItem) => { try { const preview=await api<RestorePreview>(`/trash/${encodeURIComponent(item.id)}/preview`); const collision=preview.collisions.length?`\n冲突：${preview.collisions.join('；')}`:''; if(!preview.restorable||!confirm(`恢复“${item.name}”？预计恢复 ${preview.restore_count} 项，跳过 ${preview.skip_count} 项。${collision}`)) return; const result=await api<{restored:number;skipped:number}>(`/trash/${encodeURIComponent(item.id)}/restore`,{method:'POST',body:JSON.stringify({desired_folder:''})}); notify({kind:'ok',text:`已恢复 ${result.restored} 项，跳过 ${result.skipped} 项`}); if(item.kind==='industry') location.reload(); else await load() } catch(e) { notify({kind:'error',text:String(e)}) } }
  return <><Header eyebrow="SYSTEM" title="系统状态" body="默认 Web 服务拥有持久调度、任务与恢复状态。所有自动任务只采集和生成产物，不发送邮件。" actions={<><button className="button secondary" onClick={()=>void load()}><RefreshCw/>刷新</button> <button className="button danger" onClick={shutdown}>退出 IntDog</button></>}/>
    <div className="system-grid"><StatusCard icon={Activity} label="本地 API" value={error ? '不可用' : health?.status || '检查中'} ok={!error && health?.status === 'ready'}/><StatusCard icon={Database} label="知识数据库" value={health?.database ? '已连接' : '等待初始化'} ok={Boolean(health?.database)}/><StatusCard icon={FolderKanban} label="活动任务" value={String(health?.active_jobs ?? '—')} ok={true}/><StatusCard icon={Clock3} label="自动调度" value={health?.automation_running?'运行中':'等待服务'} ok={Boolean(health?.automation_running)}/></div>
    <section className="section-card automation-panel"><div className="section-title"><div><h2>自动化计划</h2><p className="subtle">只有成功任务才推进周期；失败会指数退避并保留尝试周期、任务与错误。邮件推送已禁用。</p></div><span className="status-pill">NO EMAIL</span></div>{!industry?<Empty title="暂无当前行业" body="创建行业后即可配置自动化。" compact/>:<div className="schedule-grid">{(automation?.schedules||[]).map(schedule=><article key={schedule.action}><div><strong>{actionLabels[schedule.action]}</strong><small>下次：{schedule.next_run_at||'待计算'}<br/>最近成功：{schedule.last_success_at||'尚未运行'}{schedule.retry_count?` · 重试 ${schedule.retry_count}`:''}</small></div><label className="switch"><input type="checkbox" checked={schedule.enabled} onChange={e=>void configure(schedule,{enabled:e.target.checked})}/><span/>启用</label><label><span>本地时间</span><input type="time" value={schedule.local_time} onChange={e=>void configure(schedule,{local_time:e.target.value})}/></label>{schedule.action!=='daily'&&<><label><span>流水线</span><select value={schedule.pipeline_mode} onChange={e=>void configure(schedule,{pipeline_mode:e.target.value as Schedule['pipeline_mode']})}><option value="generate">采集并生成报告</option><option value="aggregate">仅聚合已有情报</option></select></label><label><span>模型</span><select value={schedule.provider} onChange={e=>void configure(schedule,{provider:e.target.value as Schedule['provider']})}><option value="codex">Codex 套餐</option><option value="openai">OpenAI API</option></select></label></>}<button className="button secondary" onClick={()=>void runNow(schedule.action)}>立即运行</button>{schedule.last_artifact_path&&<a className="button secondary" href={artifactUrl(schedule.last_artifact_path)} target="_blank" rel="noreferrer">打开最近产物</a>}{schedule.last_error&&<p className="field-error">{schedule.last_error}{schedule.retry_after&&<> · 下次重试 {schedule.retry_after}</>}</p>}</article>)}</div>}</section>
    <div className="two-columns"><section className="section-card system-detail"><h2>数据与信任边界</h2><dl><dt>数据目录</dt><dd>{health?.data_root || '正在读取'}</dd><dt>网络服务</dt><dd>仅监听 127.0.0.1，并验证 Host、Origin 与启动会话</dd><dt>会话保护</dt><dd>{health?.session_required?'已启用':'开发模式未注入会话凭证'}</dd><dt>实时状态</dt><dd>浏览器读取权威任务记录；空闲不等于停滞</dd></dl></section><section className="section-card industry-manager"><h2>行业管理</h2><form onSubmit={renameIndustry}><label><span>显示名称</span><input name="name" disabled={!industry}/></label><label><span>数据文件夹</span><input name="folder" defaultValue={industry} disabled={!industry} required/></label><button className="button secondary" disabled={!industry}>更新当前行业</button></form><form onSubmit={createIndustry}><label><span>新行业名称</span><input name="name" required/></label><label><span>英文或中文文件夹</span><input name="folder" required/></label><button className="button primary">新建行业</button></form><button className="button danger" disabled={!industry} onClick={archiveIndustry}>归档当前行业</button></section></div>
    <section className="section-card trash-panel"><div className="section-title"><div><h2>回收站</h2><p className="subtle">恢复优先；本轮不提供不可逆永久删除。</p></div><span>{trash.length} 条记录</span></div>{!trash.length?<Empty title="回收站为空" body="归档行业或删除每日情报后，可在这里恢复。" compact/>:<div className="trash-list">{trash.map(item=><article key={item.id}><span className="trash-kind">{item.kind==='industry'?'行业':'每日情报'}</span><div><strong>{item.name}</strong><small>{item.created_at||'时间未知'} · {item.item_count} 项 · {item.id}</small></div><button className="button secondary" onClick={()=>void restore(item)}><RotateCcw/>恢复</button></article>)}</div>}</section>
    <section className="section-card audit-panel"><div className="section-title"><div><h2>最近审计记录</h2><p className="subtle">重要写操作、人工纠正与恢复均保留主体、对象和时间。</p></div><span>{audits.length} 条</span></div>{!audits.length?<Empty title="暂无审计记录" body="执行行业、Story 或恢复操作后会出现在这里。" compact/>:<div className="audit-list">{audits.slice(0,30).map(row=><article key={row.id}><time>{row.occurred_at}</time><strong>{row.action}</strong><span>{row.actor} · {row.object_type}{row.object_id?` · ${row.object_id}`:''}</span></article>)}</div>}</section>
  </>
}

function StatusCard({ icon: Icon, label, value, ok }: { icon: LucideIcon; label: string; value: string; ok: boolean }) { return <div className="status-card"><span><Icon/></span><div><small>{label}</small><strong>{value}</strong></div><i className={ok ? 'ok' : 'warn'}/></div> }
